# Generated by Django 4.1.6 on 2023-03-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_alter_spotifytoken_expires_in'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE spotify_spotifytoken ALTER COLUMN expires_in TYPE integer USING EXTRACT(epoch FROM expires_in)::integer;',
        ),
    ]
